export default {
  languageType: 'en',
  lang: 'en',
  welcome: 'WELCOME',
  sign_in: 'Sign In',
  enter_details_below: 'Enter your details below & free sign up',
  email_address: 'Email Address',
  password: 'Password',
  forgot_password: 'Forgot Password?',
  email: 'Email',
  login: 'Login',
  reset_password: 'Reset Password',
  please_enter_email:
    'Please enter the email address associated with your account and we will email you a 5 digit code.',
  send_code: 'Send Code',
  enter_your_code: 'Enter Your Code',
  please_enter_code: 'Please enter the 5 digit code',
  resend_code_in: 'Resend code in',
  verify: 'Verify',
  back_to_login: 'Back to Login',
  didnt_receive_code: "Didn't receive the code? ",
  resend_here: 'Resend here',
  create_new_password: 'Create New Password',
  enter_your_new_password: 'Enter your new password',
  confirm_new_password: 'Confirm new password',
  confirm_password: 'Confirm Password',
  one_uppercase: 'One uppercase character',
  one_lowercase: 'One lowercase character',
  one_special_character: 'One special character',
  one_numeric_digit: 'One numeric digit',
  twelve_characters: '12 characters minimum',

  select_your_language: 'SELECT YOUR LANGUAGE',
  select_theme: 'SELECT YOUR THEME',
  phone_number_placeholder: 'Mobile Number',
  whats_your_phone_number: "What's your mobile number?",
  lets_create_your_account: 'Let’s create your account.',
  enter_mobile_number: 'Enter Mobile Number',
  enter_your_phone: 'Enter your phone',
  enter_password: 'Enter your password',
  enter_email: 'Enter your email address',
  lets_create_account: 'Let’s create your account',
  signing_energiSync_is_fast:
    'Signing up for Energi-Sync is fast and free. No commitments or long-term contracts',
  first_name: 'First name',
  last_name: 'Last name',
  enter_your_phone_number: 'Enter your phone number',
  create_password: 'Create a password',
  continue: 'Continue',
  account_created: 'Your account is being created!',
};
