export default {
  languageType: 'en',
  lang: 'en',
  welcome: 'WELCOME',
  sign_in: 'Sign In',
  enter_details_below: 'Enter your details below & free sign up',
  email_address: 'Email Address',
  username: 'User Name',
  password: 'Password',
  forgot_password: 'Forgot Password?',
  email: 'Email',
  login: 'Login',
  name: 'Name',
  reset_password: 'Reset Password',
  please_enter_email:
    'Please enter the email address associated with your account and we will email you a 5 digit code.',
  send_code: 'Send Code',
  enter_your_code: 'Enter Your Code',
  please_enter_code: 'Please enter the 5 digit code',
  resend_code_in: 'Resend code in',
  verify: 'Verify',
  back_to_login: 'Back to Login',
  didnt_receive_code: "Didn't receive the code? ",
  resend_here: 'Resend here',
  create_new_password: 'Create New Password',
  enter_your_new_password: 'Enter your new password',
  confirm_new_password: 'Confirm new password',
  confirm_password: 'Confirm Password',
  one_uppercase: 'One uppercase character',
  one_lowercase: 'One lowercase character',
  one_special_character: 'One special character',
  one_numeric_digit: 'One numeric digit',
  twelve_characters: '12 characters minimum',
  choose_language: 'Choose Language',
  english: 'English',
  spanish: 'Spanish',
  continue: 'Continue',
  sport: 'Sport',
  organization: 'Organization',
  home: 'Home',
  profile: 'Profile',
  languageSettings: 'Language Settings',
  housing: 'Housing',
  maintenance_request: 'Maintenance Request',
  arrival_instructions: 'Arrival Instructions',
  upload_DL_CC: 'Upload DL and CC',
  upload: 'Upload Driver’s License & Credit Card Picture',
  property_info: 'Property Info',
  property_name: 'Property Name',
  address: 'Address',
  property_details: 'Property Details',
  roommate_details: 'Roommate Details',
  website: 'Website',
};
