export default {
  languageType: 'es',
  lang: 'es',
  welcome: 'BIENVENIDO',
  sign_in: 'Iniciar sesión',
  enter_details_below: 'Introduce tus datos a continuación y regístrate gratis',
  email_address: 'Dirección de correo electrónico',
  password: 'Contraseña',
  forgot_password: '¿Olvidaste tu contraseña?',
  email: 'Correo electrónico',
  login: 'Iniciar sesión',
  reset_password: 'Restablecer contraseña',
  please_enter_email:
    'Por favor ingresa la dirección de correo electrónico asociada a tu cuenta y te enviaremos un código de 5 dígitos.',
  send_code: 'Enviar código',
  enter_your_code: 'Ingresa tu código',
  please_enter_code: 'Por favor ingresa el código de 5 dígitos',
  resend_code_in: 'Reenviar código en',
  verify: 'Verificar',
  back_to_login: 'Volver al inicio de sesión',
  didnt_receive_code: '¿No recibiste el código?',
  resend_here: 'Reenviar aquí',
  create_new_password: 'Crear nueva contraseña',
  enter_your_new_password: 'Ingresa tu nueva contraseña',
  confirm_new_password: 'Confirma la nueva contraseña',
  confirm_password: 'Confirmar contraseña',
  one_uppercase: 'Una letra mayúscula',
  one_lowercase: 'Una letra minúscula',
  one_special_character: 'Un carácter especial',
  one_numeric_digit: 'Un dígito numérico',
  twelve_characters: '12 caracteres mínimo',

  select_your_language: 'SELECCIONA TU IDIOMA',
  select_theme: 'SELECCIONA TU TEMA',
  phone_number_placeholder: 'Número de móvil',
  whats_your_phone_number: '¿Cuál es tu número de móvil?',
  lets_create_your_account: 'Vamos a crear tu cuenta.',
  enter_mobile_number: 'Introduce el número de móvil',
  enter_your_phone: 'Introduce tu teléfono',
  enter_password: 'Introduce tu contraseña',
  enter_email: 'Introduce tu dirección de correo electrónico',
  lets_create_account: 'Vamos a crear tu cuenta',
  signing_energiSync_is_fast:
    'Registrarse en Energi-Sync es rápido y gratuito. Sin compromisos ni contratos a largo plazo',
  first_name: 'Nombre',
  last_name: 'Apellido',
  enter_your_phone_number: 'Introduce tu número de teléfono',
  create_password: 'Crea una contraseña',
  continue: 'Continuar',
  account_created: '¡Tu cuenta está siendo creada!',
};
