export default {
  languageType: 'sp',
  lang: 'sp',
  welcome: 'BIENVENIDO',
  sign_in: 'Iniciar sesión',
  enter_details_below: 'Introduce tus datos a continuación y regístrate gratis',
  email_address: 'Dirección de correo electrónico',
  username: 'Nombre de usuario',
  password: 'Contraseña',
  forgot_password: '¿Olvidaste tu contraseña?',
  email: 'Correo electrónico',
  login: 'Iniciar sesión',
  name: 'Nombre',
  reset_password: 'Restablecer contraseña',
  please_enter_email:
    'Por favor ingresa la dirección de correo electrónico asociada a tu cuenta y te enviaremos un código de 5 dígitos.',
  send_code: 'Enviar código',
  enter_your_code: 'Ingresa tu código',
  please_enter_code: 'Por favor ingresa el código de 5 dígitos',
  resend_code_in: 'Reenviar código en',
  verify: 'Verificar',
  back_to_login: 'Volver al inicio de sesión',
  didnt_receive_code: '¿No recibiste el código?',
  resend_here: 'Reenviar aquí',
  create_new_password: 'Crear nueva contraseña',
  enter_your_new_password: 'Ingresa tu nueva contraseña',
  confirm_new_password: 'Confirma la nueva contraseña',
  confirm_password: 'Confirmar contraseña',
  one_uppercase: 'Una letra mayúscula',
  one_lowercase: 'Una letra minúscula',
  one_special_character: 'Un carácter especial',
  one_numeric_digit: 'Un dígito numérico',
  twelve_characters: '12 caracteres mínimo',
  choose_language: 'Elegir idioma',
  english: 'Inglés',
  spanish: 'Español',
  continue: 'Continuar',
  sport: 'Deporte',
  organization: 'Organización',
  home: 'Inicio',
  profile: 'Perfil',
  languageSettings: 'Configuración de idioma',
  housing: 'Vivienda',
  maintenance_request: 'Solicitud de mantenimiento',
  arrival_instructions: 'Instrucciones de llegada',
  upload_DL_CC: 'Subir licencia de conducir y tarjeta de crédito',
  upload: 'Subir imagen de la licencia de conducir y la tarjeta de crédito',

  property_info: 'Información de la propiedad',
  property_name: 'Nombre de la propiedad',
  address: 'Dirección',
  property_details: 'Detalles de la propiedad',
  roommate_details: 'Detalles del compañero de cuarto',
  website: 'Sitio web',
};
